// Mocks generated by Mockito 5.4.6 from annotations
// in clean_arch/test/features/home/data/repo/home_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:clean_arch/config/base_response/base_response.dart' as _i5;
import 'package:clean_arch/features/home/api/api_client/api_client.dart' as _i2;
import 'package:clean_arch/features/home/api/data_sources/local/home_local_datasource_impl.dart'
    as _i9;
import 'package:clean_arch/features/home/api/data_sources/remote/home_remote_datasource_impl.dart'
    as _i3;
import 'package:clean_arch/features/home/data/models/category_dto.dart' as _i8;
import 'package:clean_arch/features/home/data/models/product_dto.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHomeApiClient_0 extends _i1.SmartFake implements _i2.HomeApiClient {
  _FakeHomeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeRemoteDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDatasourceImpl extends _i1.Mock
    implements _i3.HomeRemoteDatasourceImpl {
  MockHomeRemoteDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeHomeApiClient_0(
              this,
              Invocation.getter(#apiClient),
            ),
          )
          as _i2.HomeApiClient);

  @override
  _i4.Future<_i5.BaseResponse<List<_i6.ProductDto>>> getProducts({
    bool? isSecondary = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {#isSecondary: isSecondary}),
            returnValue:
                _i4.Future<_i5.BaseResponse<List<_i6.ProductDto>>>.value(
                  _i7.dummyValue<_i5.BaseResponse<List<_i6.ProductDto>>>(
                    this,
                    Invocation.method(#getProducts, [], {
                      #isSecondary: isSecondary,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<List<_i6.ProductDto>>>);

  @override
  _i4.Future<_i5.BaseResponse<List<_i8.CategoryDto>>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue:
                _i4.Future<_i5.BaseResponse<List<_i8.CategoryDto>>>.value(
                  _i7.dummyValue<_i5.BaseResponse<List<_i8.CategoryDto>>>(
                    this,
                    Invocation.method(#getCategories, []),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<List<_i8.CategoryDto>>>);
}

/// A class which mocks [HomeLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeLocalDatasourceImpl extends _i1.Mock
    implements _i9.HomeLocalDatasourceImpl {
  MockHomeLocalDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.BaseResponse<dynamic>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i4.Future<_i5.BaseResponse<dynamic>>.value(
              _i7.dummyValue<_i5.BaseResponse<dynamic>>(
                this,
                Invocation.method(#getCategories, []),
              ),
            ),
          )
          as _i4.Future<_i5.BaseResponse<dynamic>>);

  @override
  _i4.Future<_i5.BaseResponse<dynamic>> getProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, []),
            returnValue: _i4.Future<_i5.BaseResponse<dynamic>>.value(
              _i7.dummyValue<_i5.BaseResponse<dynamic>>(
                this,
                Invocation.method(#getProducts, []),
              ),
            ),
          )
          as _i4.Future<_i5.BaseResponse<dynamic>>);
}
